version: "2"
linters:
  default: standard   # errcheck, govet, staticcheck, unused, ineffassign
  enable:
    - errorlint       # %w e errors.Is/As corretos
    - gocritic
    - gosec
    - misspell
    - revive
    - unparam
    - nilerr
  settings:
    revive:
      rules:
        - name: exported
          disabled: true   # habilite se for lib publica
formatters:
  enable:
    - gofumpt
    - goimports
